# Generated by Django 5.1.3 on 2024-12-09 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='browsinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commenthistory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish'),
        ),
        migrations.AddField(
            model_name='browsinghistory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish'),
        ),
        migrations.AddField(
            model_name='favoritehistory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish'),
        ),
        migrations.AddField(
            model_name='favoritehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.dish'),
        ),
        migrations.AddField(
            model_name='likehistory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish'),
        ),
        migrations.AddField(
            model_name='likehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(related_name='dishes', to='api.tag'),
        ),
    ]
