# Generated by Django 5.1.3 on 2024-12-08 08:22

from django.db import migrations

def create_initial_data(apps, schema_editor):
    Tag = apps.get_model('api', 'Tag')
    Dish = apps.get_model('api', 'Dish')
    Image = apps.get_model('api', 'Image')

    # 定义标签数据
    tags_data = [
        {'name': '辣', 'name_en': 'Spicy'},
        {'name': '受欢迎', 'name_en': 'Popular'},
        {'name': '川菜', 'name_en': 'Sichuan Cuisine'},
        {'name': '开胃菜', 'name_en': 'Appetizer'},
        {'name': '主菜', 'name_en': 'Main Course'},
        {'name': '素食', 'name_en': 'Vegetarian'},
        {'name': '肉类', 'name_en': 'Meat'},
        {'name': '海鲜', 'name_en': 'Seafood'},
        {'name': '火锅', 'name_en': 'Hot Pot'},
        {'name': '传统', 'name_en': 'Traditional'},
        {'name': '特色', 'name_en': 'Signature'},
        {'name': '麻', 'name_en': 'Numbing'},
        {'name': '鲜', 'name_en': 'Savory'},
        {'name': '汤', 'name_en': 'Soup'},
        {'name': '风味', 'name_en': 'Flavorful'},
        {'name': '甜品', 'name_en': 'Dessert'},
        {'name': '小吃', 'name_en': 'Snack'},
    ]

    # 创建标签并储存到字典中以便后续引用
    tag_objects = {}
    for t_data in tags_data:
        t, _ = Tag.objects.get_or_create(name=t_data['name'], defaults={'name_en': t_data['name_en']})
        tag_objects[t.name] = t

    # 定义菜品数据
    dishes_data = [
        {
            'name': '泡菜',
            'name_en': 'Sichuan Pickles',
            'description': '一种传统的四川开胃菜，将蔬菜在调味盐水中发酵，口味酸辣爽口。',
            'description_en': 'A traditional Sichuan appetizer made by fermenting vegetables in seasoned brine, giving them a tangy and spicy flavor.',
            'tags': ['川菜', '开胃菜', '素食'],
            'images': ['http://example.com/images/paocai1.jpg']
        },
        {
            'name': '水煮鱼',
            'name_en': 'Boiled Fish in Chili Oil',
            'description': '经典的四川菜肴，鱼片在充满辣椒和花椒的麻辣汤中煮制，鱼肉鲜嫩。',
            'description_en': 'A classic Sichuan dish featuring tender slices of fish poached in a spicy and numbing broth filled with chili peppers and Sichuan peppercorns.',
            'tags': ['辣', '川菜', '主菜', '海鲜', '麻'],
            'images': ['http://example.com/images/shuizhuyu1.jpg']
        },
        {
            'name': '香辣牛蛙',
            'name_en': 'Spicy Bullfrog',
            'description': '牛蛙肉与香辣酱炒制，常伴有辣椒和香料，口感独特。',
            'description_en': 'Bullfrog meat stir-fried with a fragrant and spicy sauce, often featuring chili peppers and aromatic spices.',
            'tags': ['辣', '川菜', '主菜', '肉类', '风味'],
            'images': ['http://example.com/images/xianglaniuwa1.jpg']
        },
        {
            'name': '毛血旺',
            'name_en': 'Mao Xue Wang',
            'description': '以鸭血、毛肚等食材为主料的麻辣火锅，味道鲜香麻辣。',
            'description_en': 'A spicy hot pot dish featuring duck blood, tripe, and other ingredients, with a savory and numbing flavor.',
            'tags': ['辣', '川菜', '主菜', '火锅', '麻'],
            'images': ['http://example.com/images/maoxuewang1.jpg']
        },
        {
            'name': '水煮牛肉',
            'name_en': 'Boiled Beef in Chili Oil',
            'description': '嫩滑的牛肉片在麻辣的汤汁中煮制，香气四溢。',
            'description_en': 'Tender slices of beef poached in a spicy and numbing broth, releasing a rich aroma.',
            'tags': ['辣', '川菜', '主菜', '肉类', '麻'],
            'images': ['http://example.com/images/shuizhuniurou1.jpg']
        },
        {
            'name': '水煮肉片',
            'name_en': 'Boiled Pork Slices in Chili Oil',
            'description': '薄切猪肉在麻辣汤汁中煮制，鲜香辛辣。',
            'description_en': 'Thinly sliced pork poached in a spicy and numbing broth, offering a savory and hot flavor.',
            'tags': ['辣', '川菜', '主菜', '肉类', '麻'],
            'images': ['http://example.com/images/shuizhuroupian1.jpg']
        },
        {
            'name': '香辣虾',
            'name_en': 'Spicy Shrimp',
            'description': '鲜虾与香辣酱炒制，味道鲜美辛辣。',
            'description_en': 'Fresh shrimp stir-fried with a spicy and fragrant sauce, offering a delicious and hot flavor.',
            'tags': ['辣', '川菜', '主菜', '海鲜', '风味'],
            'images': ['http://example.com/images/xianglaxi1.jpg']
        },
        {
            'name': '辣子鸡',
            'name_en': 'Spicy Chicken',
            'description': '鸡肉与大量辣椒和花椒炒制，香脆麻辣。',
            'description_en': 'Chicken stir-fried with a large amount of chili peppers and Sichuan peppercorns, resulting in a crispy and numbing spiciness.',
            'tags': ['辣', '川菜', '主菜', '肉类', '麻'],
            'images': ['http://example.com/images/laziji1.jpg']
        },
        {
            'name': '香辣肥肠',
            'name_en': 'Spicy Pork Intestines',
            'description': '猪肥肠与香辣酱炒制，口感丰富麻辣。',
            'description_en': 'Pork intestines stir-fried with a spicy and fragrant sauce, offering a rich and numbing flavor.',
            'tags': ['辣', '川菜', '主菜', '肉类', '麻'],
            'images': ['http://example.com/images/xianglafichang1.jpg']
        },
        {
            'name': '豆花',
            'name_en': 'Tofu Pudding',
            'description': '嫩滑的豆腐配以特制的调料，口感细腻。',
            'description_en': 'Silky tofu served with special seasonings, offering a delicate texture.',
            'tags': ['开胃菜', '川菜', '素食', '汤'],
            'images': ['http://example.com/images/douhua1.jpg']
        },
        {
            'name': '蒜泥白肉',
            'name_en': 'Garlic Pork Slices',
            'description': '薄切猪肉配以蒜泥和特制酱料，鲜香微辣。',
            'description_en': 'Thinly sliced pork served with garlic paste and special sauces, offering a savory and mildly spicy flavor.',
            'tags': ['开胃菜', '川菜', '主菜', '肉类', '风味'],
            'images': ['http://example.com/images/suanmibaierou1.jpg']
        },
        {
            'name': '回锅肉',
            'name_en': 'Twice-Cooked Pork',
            'description': '煮熟后再炒制的猪肉片，香气浓郁。',
            'description_en': 'Pork slices first boiled and then stir-fried, resulting in a rich aroma.',
            'tags': ['川菜', '主菜', '肉类', '传统', '风味'],
            'images': ['http://example.com/images/huiguorou1.jpg']
        },
        {
            'name': '鱼香肉丝',
            'name_en': 'Yu Xiang Shredded Pork',
            'description': '猪肉丝配以鱼香酱料，酸甜辛辣。',
            'description_en': 'Shredded pork served with Yu Xiang sauce, offering a sweet, sour, and spicy flavor.',
            'tags': ['辣', '川菜', '主菜', '肉类', '风味'],
            'images': ['http://example.com/images/yuxiangrousi1.jpg']
        },
        {
            'name': '鸡杂',
            'name_en': 'Chicken Offal',
            'description': '多种鸡内脏炖煮，香辣可口。',
            'description_en': 'Various chicken offal stewed in a spicy broth, offering a flavorful taste.',
            'tags': ['辣', '川菜', '主菜', '肉类', '麻'],
            'images': ['http://example.com/images/jiza1.jpg']
        },
        {
            'name': '麻婆豆腐',
            'name_en': 'Mapo Tofu',
            'description': '嫩豆腐与牛肉末在麻辣酱汁中煮制，鲜香麻辣。',
            'description_en': 'Silky tofu cooked with ground beef in a spicy and numbing sauce, offering a savory and hot flavor.',
            'tags': ['辣', '川菜', '主菜', '素食', '麻'],
            'images': ['http://example.com/images/mapodoufu1.jpg']
        },
        {
            'name': '麻辣鸭血',
            'name_en': 'Spicy Duck Blood',
            'description': '鸭血与蔬菜在麻辣汤汁中煮制，鲜香麻辣。',
            'description_en': 'Duck blood cooked with vegetables in a spicy and numbing broth, offering a fresh and hot flavor.',
            'tags': ['辣', '川菜', '主菜', '海鲜', '麻'],
            'images': ['http://example.com/images/maladayaxue1.jpg']
        }
    ]

    # 创建标签对象并存储到字典中
    tag_objects = {}
    for t_data in tags_data:
        t, _ = Tag.objects.get_or_create(name=t_data['name'], defaults={'name_en': t_data['name_en']})
        tag_objects[t.name] = t

    # 创建菜品和关联数据
    for dish_data in dishes_data:
        dish, _ = Dish.objects.get_or_create(
            name=dish_data['name'],
            defaults={
                'name_en': dish_data['name_en'],
                'description': dish_data['description'],
                'description_en': dish_data['description_en']
            }
        )
        # 添加标签
        dish_tags = [tag_objects[tag_name] for tag_name in dish_data['tags']]
        dish.tags.set(dish_tags)
        # 添加图片
        for image_url in dish_data['images']:
            Image.objects.get_or_create(dish=dish, image_url=image_url)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dish_description_en_dish_name_en_tag_name_en'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
