# Generated by Django 5.1.3 on 2024-12-16 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20241210_1441'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('LIKE', '喜爱'), ('DISLIKE', '不喜爱'), ('OTHER', '其他')], max_length=7)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_preferences', to='api.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tag')},
            },
        ),
    ]
