# Generated by Django 5.1.3 on 2024-12-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dietarypreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritehistory',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_histories', to='api.dish'),
        ),
    ]
