# Generated by Django 5.1.3 on 2024-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_commenthistory_rating_alter_commenthistory_dish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimage',
            name='image',
        ),
        migrations.AddField(
            model_name='commentimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
