# Generated by Django 5.1.3 on 2024-12-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list, help_text='用户的饮食禁忌列表（字符串列表）', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='religious_belief',
            field=models.CharField(blank=True, help_text='用户的宗教信仰', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='signup_date',
            field=models.DateField(blank=True, help_text='用户注册日期（年月日）', null=True),
        ),
    ]
