# Generated by Django 5.1.3 on 2024-12-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dietarypreference'),
        ('users', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dietary_restrictions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, help_text='用户的饮食偏好（喜爱、不喜爱、其他）', related_name='users_with_preferences', through='api.DietaryPreference', to='api.tag'),
        ),
    ]
